DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS news_article;

CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL, 
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE news_article (
    id INT PRIMARY KEY AUTO_INCREMENT,
    author_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(255) NOT NULL,
    banner_filename VARCHAR(255),
    content TEXT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user(id)
);